apiVersion: v1
kind: Pod
metadata:
    name: mongodb
    labels:
        app: mongodb
spec:
    containers:
    - name: mongodb
      image: docker.io/library/mongo:latest
      args: ["--bind_ip_all"]
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
      ports:
        - containerPort: 27017
          hostPort: 27017
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
    volumes:
        - name: mongo-data
          hostPath:
            path: ./data/mongodb
            type: DirectoryOrCreate



